searchify/urls.py
from django.contrib import admin
from django.urls import path, include  

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('searchifyApp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

searchifyApp/urls.py
from django.urls import path
from . import views

# URLs of this App
app_name = "searchifyApp"
urlpatterns = [
    path("", views.index, name="index"),
    path("share/", views.create, name="share"),
    path("search/", views.search, name="search"),
    path("searchTag/", views.searchTag, name="searchTag"),
    path("searchContent/", views.searchContent, name="searchContent"),
    path("result/<str:tag>/", views.result, name="result"),
    path("contentResult/<str:content>/", views.contentResult, name="contentResult"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("find", views.find, name="find"),
    path("userlist/<str:username>/", views.userlist, name="userlist"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register")

]

searchifyApp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Relational Database Model: User, Post, Tag
class User(AbstractUser):
    pass

class Post(models.Model):
    content = models.CharField(max_length=64)
    poster = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    timestamp = models.DateField(auto_now_add=True)
    image = models.ImageField(null=False, blank=False, default="No Images", upload_to="images/")

class Tag(models.Model):
    tag = models.CharField(max_length=32, default=None)
    tag_post = models.ManyToManyField(Post, related_name="tagged_posts")

searchifyApp/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post, Tag, User

# Use for uploading image with content 
class SnapCreationForm(ModelForm):
    class Meta:
        model = Post
        fields = ('content', 'image',)

# Use for including tags for the image being uploaded
class tagCreationForm(ModelForm):
    class Meta:
        model = Tag
        fields = ('tag',)

# Use for searching images by tags
class searchForm(ModelForm):
    class Meta:
        model = Tag
        fields = ('tag',)

# Use for searching content by tags
class contentSearchForm(ModelForm):
    class Meta:
        model = Post
        fields = ('content',)

# Use for searching users/profiles by sub/string
class findForm(forms.Form):
    name_user = forms.CharField(max_length=100)

searchifyApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from .forms import SnapCreationForm, tagCreationForm, searchForm, findForm, contentSearchForm

from .models import User, Post, Tag

# Homepage, display all images
def index(request):
    post_list = Post.objects.all()
    return render(request, "searchifyApp/index.html", {
        'post_list':post_list
    })

# Search for users/profiles by sub/string, authentication required
def find(request):
    if request.method == "POST":
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse('searchifyApp:login'))
        else:
            form = findForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('name_user')
                return HttpResponseRedirect(reverse('searchifyApp:userlist', kwargs={'username':username}))
            
    return render(request, "searchifyApp/find.html", {
        'form':findForm,
    })

# Display users/profiles containing the case-insensitive substring/search word, auth in template
def userlist(request, username):
    userlist = User.objects.filter(username__icontains = username)
    return render(request, "searchifyApp/userlist.html", {
        'form':findForm,
        'userlist':userlist,
        'searchName':username
    })

# Display specific user/profile, auth in template
def profile(request, username):
    try:
        username = User.objects.get(username=username)
    except User.DoesNotExist:
        raise Http404("Profile not found.")
    user_post_list = Post.objects.filter(poster__username=username)

    return render(request, "searchifyApp/profile.html", {
        'post_list':user_post_list,
        'profileName':username,
    })

# Display tag-specific images by their tag(s), auth in template
def result(request, tag):
    # Separate input string into multiple tags
    tagList=tag.split()
    tagged_posts = Post.objects.filter(tagged_posts__tag__in = tagList)

    return render(request, "searchifyApp/result.html", {
        'post_list':tagged_posts,
        'tag':tag
    }) 

# Display content-specific images by case-insensitive content, auth in template
def contentResult(request, content):
    content_posts = Post.objects.filter(content__icontains = content)
    return render(request, "searchifyApp/contentResult.html", {
        'post_list':content_posts,
        'content':content
    })                       

# Display search options, auth in template
def search(request):
    return render(request, "searchifyApp/search.html", {
    })

# Search for images by tag(s), authentication required
def searchTag(request):
    if request.method == "POST":
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse('searchifyApp:login'))
        else:
            form = searchForm(request.POST)
            if form.is_valid():
                tag = form.cleaned_data.get('tag')
                return HttpResponseRedirect(reverse('searchifyApp:result', kwargs={'tag':tag}))
   
    return render(request, "searchifyApp/searchTag.html", {
        'form':searchForm,
    })

# Search for images by case-insensitive content/text, authentication required
def searchContent(request):
    if request.method == "POST":
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse('searchifyApp:login'))
        else:
            form = contentSearchForm(request.POST)
            if form.is_valid():
                content = form.cleaned_data.get('content')
                return HttpResponseRedirect(reverse('searchifyApp:contentResult', kwargs={'content':content}))
   
    return render(request, "searchifyApp/searchContent.html", {
        'form':contentSearchForm,
    })

# Creating image with content and tags, authentication required
def create(request):
    if request.method == "POST":
        # Authentication check
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse('searchifyApp:login'))
        else: 
            form = SnapCreationForm(request.POST, request.FILES)
            tagForm = tagCreationForm(request.POST)

            if form.is_valid() and tagForm.is_valid():
                tagValues = tagForm.cleaned_data.get('tag')
                form = form.save(commit=False)
                form.poster = request.user
                form.save()
                # Split by whitespace and store in DB
                tagArray = tagValues.split()
                # Add tag relations to the image
                for tagValue in tagArray:
                    # If tag doesn't already exists, then create.
                    newTag = Tag.objects.get_or_create(tag=tagValue)
                    relatedTag = Tag.objects.get(tag=tagValue)
                    form.tagged_posts.add(relatedTag)

                return redirect("/")

    return render(request, 'searchifyApp/create.html', {
        'createform':SnapCreationForm, 
        'tagform': tagCreationForm,
    })

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("searchifyApp:index"))
        else:
            return render(request, "searchifyApp/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "searchifyApp/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("searchifyApp:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "searchifyApp/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "searchifyApp/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("searchifyApp:index"))
    else:
        return render(request, "searchifyApp/register.html")

searchifyApp/templates/searchifyApp/contentResult.html
{% extends "searchifyApp/layout.html" %}
{% load static %}

{% block title %}
Search Results
{% endblock %}

{% block banner %}
    <!-- Banner -->
    <section id="banner">
        <header>
            <h2 class="resultHeader">Search Results: {{ content }}</h2>
        </header>
    </section>
{% endblock %}

{% block body %}
<div class="instagram">
    <!-- Display images with search word in content -->
    {% for post in post_list %}
    <figure class="figure col-3">
        <img src="{{ post.image.url }}" class="figure-img img-fluid rounded" alt="">
        <figcaption class="figure-caption text-right">
            {{ post.content }}
            <span class="photoTag">
                <!-- Display tags that belong to the image -->
                {% for tag in post.tagged_posts.all %}
                <a class="photoTagColor text-decoration-none" href="{% url 'searchifyApp:result' tag.tag%}">
                    #{{ tag.tag }}
                </a>
                {% endfor %}
            </span>
        </figcaption>
    </figure>
    {% endfor %}
</div>
{% endblock %}

{% block script %}
{% endblock %}

searchifyApp/templates/searchifyApp/create.html
{% extends "searchifyApp/layout.html" %}
{% load static %}

{% block title %}
Share Snaps
{% endblock %}

{% block body %}
<!-- Send user to login page if not logged in -->
{% if not request.user.is_authenticated %}
<script>
    window.location.href = '{% url "searchifyApp:login" %}';
</script>
{% endif %}

<div class="p-4 rounded col-lg-10 mx-auto">
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-form-mb-4">Snap Today</legend>
            <!-- Forms for content, an image, and multiple tags input-->
            <div class="shareForm"> 
                {{ createform.as_p }}
                Tags: {{ tagform.tag }}
            </div>
            
        </fieldset>
        <div class="form-group shareForm">
            <button type="submit" class="btn btn-primary">Post</button>
        </div>
    </form>
</div>

{% endblock %}

searchifyApp/templates/searchifyApp/find.html
{% extends "searchifyApp/layout.html" %}
{% load static %}

{% block title %}
Search Users
{% endblock %}

{% block body %}
<!-- Send user to login page if not logged in -->
{% if not request.user.is_authenticated %}
<script>
    window.location.href = '{% url "searchifyApp:login" %}';
</script>
{% endif %}

<div class="p-4 rounded col-lg-10 mx-auto">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-form-mb-4">Find Users</legend>
            <!-- Form for searching user profile-->
            <div class="searchForm"> 
               Username: {{ form.name_user }}
            </div>
            
        </fieldset>
        <div class="form-group searchForm">
            <button type="submit" class="btn btn-primary">Post</button>
        </div>
    </form>
</div>

{% endblock %}

searchifyApp/templates/searchifyApp/index.html
{% extends "searchifyApp/layout.html" %}
{% load static %}

{% block title %}
Searchify
{% endblock %}

{% block banner %}
    <!-- Banner -->
    <section id="banner">
        <header>
            <h1 class='indexHeader'>Welcome to Searchify</h1>
        </header>
    </section>
{% endblock %}

{% block body %}
<div class="instagram">
    <!-- Display all images -->
    {% for post in post_list %}
    <figure class="figure col-3">
        <img src="{{ post.image.url }}" class="figure-img img-fluid rounded" alt="">
        <figcaption class="figure-caption text-right">
            {{ post.content }}
            <span class="photoTag">
                <!-- Display tags that belong to the image -->
                {% for tag in post.tagged_posts.all %}
                <a class="photoTagColor text-decoration-none" href="{% url 'searchifyApp:result' tag.tag%}">
                    #{{ tag.tag }}
                </a>
                {% endfor %}
            </span>
        </figcaption>
    </figure>
    {% endfor %}


    <!-- As a demonstration, the media/static root that stores the images are in a separate location, 
        static/images, simulating cloud services like Amazon S3. The Heroku filesystem used here is 
        ephemeral however - hat means images uploaded will only last 24hours after being uploaded, 
        therefore the first 7 posts are hard coded for visual and demonstration purposes and will not 
        be searchable. Otherwise, feel free to register an account, upload, share, and searchify! -->

    <!-- Display all images -->   
    <figure class="figure col-3">
        <img src="https://boltgamer.com/wp-content/uploads/2020/08/pexels-xxss-is-back-777001-1024x683.jpg.webp?x38295" class="figure-img img-fluid rounded" alt="">
        <figcaption class="figure-caption text-right">
            Dual screen is the way to go!
            <span class="photoTag">
                <!-- Display tags that belong to the image -->       
                <a class="photoTagColor text-decoration-none" href="/result/Computer/">
                    #Computer</a>                    
            </span>
        </figcaption>
    </figure>

    <figure class="figure col-3">
        <img src="https://www.intelligent.co.uk/storage/app/media/uploaded-files/coffee-shop-with-light-sign-in-alleyway.jpg" class="figure-img img-fluid rounded" alt="">
        <figcaption class="figure-caption text-right">
            Post Covid19 Coffee Time.
            <span class="photoTag">
                <!-- Display tags that belong to the image -->
                <a class="photoTagColor text-decoration-none" href="/result/Coffee/">
                    #Coffee</a> 
                <a class="photoTagColor text-decoration-none" href="/result/Food/">
                    #Food</a>
            </span>
        </figcaption>
    </figure>
    
    <figure class="figure col-3">
        <img src="https://employee-experience-store.com/en/wp-content/uploads/sites/3/pexels-flo-dahm-699459-scaled-e1606832417147.jpg" class="figure-img img-fluid rounded" alt="">
        <figcaption class="figure-caption text-right">
            Late night photoshoot fun :)
            <span class="photoTag">
                <!-- Display tags that belong to the image -->
                <a class="photoTagColor text-decoration-none" href="/result/Computer/">
                    #Computer</a>
                <a class="photoTagColor text-decoration-none" href="/result/Onset/">
                    #Onset</a>
            </span>
        </figcaption>
    </figure>
    
    <figure class="figure col-3">
        <img src="https://miro.medium.com/max/10944/1*3pPbpV5jpowY1iIzDVel0g.jpeg" class="figure-img img-fluid rounded" alt="">
        <figcaption class="figure-caption text-right">
            Live. Breathe. Create.
            <span class="photoTag">
                <!-- Display tags that belong to the image -->
                <a class="photoTagColor text-decoration-none" href="/result/Inspiration/">
                    #Inspiration
                </a>
            </span>
        </figcaption>
    </figure>
    
    <figure class="figure col-3">
        <img src="https://miro.medium.com/max/10368/1*SZA5bmN2_VTv_eVBNdz-2A.jpeg" class="figure-img img-fluid rounded" alt="">
        <figcaption class="figure-caption text-right">
            Back in time.
            <span class="photoTag">
                <a class="photoTagColor text-decoration-none" href="/result/Museum/">
                    #Museum</a>
            </span>
        </figcaption>
    </figure>
    
    <figure class="figure col-3">
        <img src="https://miro.medium.com/max/6300/1*r4WfbRe59kPO1is6Kt1fag.jpeg" class="figure-img img-fluid rounded" alt="">
        <figcaption class="figure-caption text-right">
            Starring pineapple
            <span class="photoTag">
                <a class="photoTagColor text-decoration-none" href="/result/Food/">
                    #Food</a>
                <a class="photoTagColor text-decoration-none" href="/result/Onset/">
                    #Onset</a>
            </span>
        </figcaption>
    </figure>
    
    <figure class="figure col-3">
        <img src="https://thewebserv.com/wp-content/uploads/2021/03/steam-for-cough-1.jpg" class="figure-img img-fluid rounded" alt="">
        <figcaption class="figure-caption text-right">
            Feeling a bit hungry.
            <span class="photoTag">                
                <a class="photoTagColor text-decoration-none" href="/result/Food/">
                    #Food</a> 
            </span>
        </figcaption>
    </figure>
    
    <figure class="figure col-3">
        <img src="https://strykerdesign.weebly.com/uploads/1/3/2/5/132513037/dimentional-letters-pflugerville-tx.jpg" class="figure-img img-fluid rounded" alt="">
        <figcaption class="figure-caption text-right">
            @STUDIO
            <span class="photoTag">                
                <a class="photoTagColor text-decoration-none" href="/result/Inspiration/">
                    #Inspiration</a>
                <a class="photoTagColor text-decoration-none" href="/result/Onset/">
                    #Onset</a>
            </span>
        </figcaption>
    </figure>
    <!-- Initial demo image ends -->

</div>
{% endblock %}

{% block script %}
{% endblock %}

searchifyApp/templates/searchifyApp/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Searchify{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'searchifyApp/styles.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

        {% block script %}
        {% endblock %}
    </head>
    <body>
        <!-- App name -->
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand" href="{% url 'searchifyApp:index' %}">Searchify</a>
            
            <div>
              <ul class="navbar-nav mr-auto">
                <!-- Options for authenticated user -->
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'searchifyApp:profile' user.username%}"><strong>{{ user.username }}</strong></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'searchifyApp:index' %}">All InstaSnaps</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'searchifyApp:share' %}">Share Snaps</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'searchifyApp:search' %}">Search</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'searchifyApp:find' %}">Friends</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'searchifyApp:logout' %}">Log Out</a>
                </li>
                <!-- Options for users not authenticated -->
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'searchifyApp:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'searchifyApp:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
        </nav>
        
        {% block banner %}
        {% endblock %}

        {% block profile %}
        {% endblock %}

        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

searchifyApp/templates/searchifyApp/login.html
{% extends "searchifyApp/layout.html" %}

{% block body %}
<div class='loginDiv'>
    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'searchifyApp:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>
    <!-- Register link -->
    Don't have an account? <a href="{% url 'searchifyApp:register' %}">Register here.</a>
</div>
{% endblock %}

searchifyApp/templates/searchifyApp/profile.html
{% extends "searchifyApp/layout.html" %}
{% load static %}

{% block title %}
Profile: {{ profileName }}
{% endblock %}

{% block banner %}
    <!-- Banner -->
    <section id="banner">
        <header>
            <h1 class='indexHeader'>Welcome to <span class="profileName">{{ profileName }}</span> Searchify</h1>
        </header>
    </section>
{% endblock %}

{% block body %}

{% if request.user.is_authenticated %}
<div class="instagram">
    <!-- Display images for this user/profile -->
    {% for post in post_list %}
    <figure class="figure col-3">
        <img src="{{ post.image.url }}" class="figure-img img-fluid rounded" alt="">
        <figcaption class="figure-caption text-right">
            {{ post.content }}
            <span class="photoTag">
                <!-- Display image's tags -->
                {% for tag in post.tagged_posts.all %}
                <a class="photoTagColor text-decoration-none" href="{% url 'searchifyApp:result' tag.tag%}">
                    #{{ tag.tag }}
                </a>
                {% endfor %}
            </span>
        </figcaption>
    </figure>
    {% endfor %}
</div>
{% else %}
<div class="instagram">
    Don't have an account? <a href="{% url 'searchifyApp:register' %}">Register here.</a></div>
{% endif %}
{% endblock %}

{% block script %}
{% endblock %}

searchifyApp/templates/searchifyApp/register.html
{% extends "searchifyApp/layout.html" %}

{% block body %}
<div class='registerDiv'>
    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'searchifyApp:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>
    <!-- Login link -->
    Already have an account? <a href="{% url 'searchifyApp:login' %}">Log In here.</a>
</div>
{% endblock %}

searchifyApp/templates/searchifyApp/result.html
{% extends "searchifyApp/layout.html" %}
{% load static %}

{% block title %}
Search Results
{% endblock %}

{% block banner %}
    <!-- Banner -->
    <section id="banner">
        <header>
            <h2 class="resultHeader">Search Results: {{ tag }}</h2>
        </header>
    </section>
{% endblock %}

{% block body %}

<div class="instagram">
    <!-- Display image search results for specific tags -->
    {% for post in post_list %}
    <figure class="figure col-3">
        <img src="{{ post.image.url }}" class="figure-img img-fluid rounded" alt="">
        <figcaption class="figure-caption text-right">
            {{ post.content }}
            <span class="photoTag">
                <!-- Display tags for the image -->
                {% for tag in post.tagged_posts.all %}
                <a class="photoTagColor text-decoration-none" href="{% url 'searchifyApp:result' tag.tag%}">
                    #{{ tag.tag }}
                </a>
                {% endfor %}
            </span>
        </figcaption>
    </figure>
    {% endfor %}

</div>
{% endblock %}

{% block script %}
{% endblock %}

searchifyApp/templates/searchifyApp/search.html
{% extends "searchifyApp/layout.html" %}
{% load static %}

{% block title %}
Search Snaps
{% endblock %}

{% block body %}

{% if not request.user.is_authenticated %}
<script>
    window.location.href = '{% url "searchifyApp:login" %}';
</script>
{% endif %}

<!-- Search options: Content, Tags -->
<div class="p-4 rounded col-lg-10 mx-auto">
    <ul class="list-group">
        <a class="text-decoration-none" href="{% url 'searchifyApp:searchContent' %}">
            <li class="list-group-item list-group-item-action">
                Search by Content
            </li>
        </a>
        <a class="text-decoration-none" href="{% url 'searchifyApp:searchTag' %}">
            <li class="list-group-item list-group-item-action">
                Search by Tags
            </li>
        </a>
    </ul>
</div>

{% endblock %}

searchifyApp/templates/searchifyApp/searchContent.html
{% extends "searchifyApp/layout.html" %}
{% load static %}

{% block title %}
Search Snaps
{% endblock %}

{% block body %}

{% if not request.user.is_authenticated %}
<script>
    window.location.href = '{% url "searchifyApp:login" %}';
</script>
{% endif %}

<!-- Form to search by Content -->
<div class="p-4 rounded col-lg-10 mx-auto">
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-form-mb-4">Search</legend>
            <div class="searchForm"> 
               {{ form.as_p }}
            </div>
        </fieldset>
        <div class="form-group searchForm">
            <button type="submit" class="btn btn-primary">Post</button>
        </div>
    </form>
</div>

{% endblock %}

searchifyApp/templates/searchifyApp/searchTag.html
{% extends "searchifyApp/layout.html" %}
{% load static %}

{% block title %}
Search Snaps
{% endblock %}

{% block body %}

{% if not request.user.is_authenticated %}
<script>
    window.location.href = '{% url "searchifyApp:login" %}';
</script>
{% endif %}

<!-- Form to search by Tags -->
<div class="p-4 rounded col-lg-10 mx-auto">
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-form-mb-4">Search</legend>
            <div class="searchForm"> 
               {{ form.as_p }}
            </div>  
        </fieldset>
        <div class="form-group searchForm">
            <button type="submit" class="btn btn-primary">Post</button>
        </div>
    </form>
</div>

{% endblock %}

searchifyApp/templates/searchifyApp/userlist.html
{% extends "searchifyApp/layout.html" %}
{% load static %}

{% block title %}
User List
{% endblock %}

{% block body %}

{% if request.user.is_authenticated %}
<div class="instagram">
    <ul class="list-group">
        <!-- Display the input from user -->
        <h2 class="resultHeader">Search Results: {{ searchName }}</h2>
        <!-- Display a list of found users -->
        {% for user in userlist %}
        <a href="{% url 'searchifyApp:profile' user %}" class="text-decoration-none">
            <li class="list-group-item">{{ user }}</li>
        </a>
        {% endfor %}
    </ul>
</div>
{% else %}
<div class="instagram">
    Don't have an account? <a href="{% url 'searchifyApp:register' %}">Register here.</a></div>
{% endif %}
{% endblock %}

{% block script %}
{% endblock %}